[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  node_bundler = "esbuild"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "authorization, content-type, x-requested-with"
    Access-Control-Allow-Methods = "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    Access-Control-Max-Age = "86400"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
