[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

# ✅ Expliciete SPA rewrites
[[redirects]]
  from = "/accept-invite"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/auth/callback"
  to = "/index.html"
  status = 200

# ✅ Catch-all (laatste regel)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
