[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

  # 👇 Specifieke SPA-rewrite voor de accept-invite route
[[redirects]]
  from = "/accept-invite"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
